name: Jugger Argentina
title: Jugger Argentina
header: Jugger Argentina

#theme: jekyll-theme-cayman
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
layout: "default"
