name: AJULP - Asociación de Jugger de La Plata
title: AJULP - Asociación de Jugger de La Plata
header: AJULP - Asociación de Jugger de La Plata

#theme: jekyll-theme-cayman
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
layout: "default"
